trigger:
  - main  # Käynnistyy automaattisesti, kun main-haaraan tulee muutoksia

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'        # Missä index.html on (juurikansio)
      output_location: ''      # Jätetään tyhjäksi pelkälle HTML-sivulle
      azure_static_web_apps_api_token: $(SWA_TOKEN) # Viittaa äsken luomaamme salaiseen muuttujaan
